### ISSUE TITLE
Macro commands should take care of different user name

### ISSUE THREAD

**Issue by michelegz** [gab-3d/Gab3d-Klipper-Utilities#2]
If your username is different from "pi", you get the error
`// sh: 0: Can't open /home/pi/Gab3d-Klipper-Utilities/backup_config.sh`
when launching the macro

**Comment by GabrieleCastellani** [comment]
thanks fixing it

**Comment by GabrieleCastellani** [comment]
Fixed in v0.0.23

**Comment by michelegz** [comment]
Tested and working perfectly, thank you!
