### ISSUE TITLE
gcode_shell_command delete_old_raw_data

### ISSUE THREAD

**Issue by v0nsild** [gab-3d/Gab3d-Klipper-Utilities#3]
Hi,

I'm getting this error after updating

Section 'gcode_shell_command delete_old_raw_data' is not a valid config section

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

It seems that these commands are being used in your gab3d utilities config for input shaping.

**Comment by nicolars** [comment]
And how did you solve the problem??
